# Generated by Django 4.0.1 on 2022-02-11 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_setting_contact_alter_setting_aboutus_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setting',
            name='facebook',
        ),
    ]
