# Generated by Django 4.0.1 on 2022-02-11 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_setting_facebook'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='facebook',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
