# Generated by Django 4.0.1 on 2022-02-11 05:33

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_setting_facebook'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setting',
            name='aboutus',
        ),
        migrations.AddField(
            model_name='setting',
            name='aboutme',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=1),
            preserve_default=False,
        ),
    ]
