# Generated by Django 4.0.1 on 2022-02-17 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_contactformmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactformmessage',
            name='message',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='contactformmessage',
            name='status',
            field=models.CharField(choices=[('New', 'Yeni'), ('Read', 'Okundu'), ('Closed', 'Kapandı')], default='New', max_length=10),
        ),
    ]
