# Generated by Django 4.0.1 on 2022-02-22 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_contactformmessage_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='linkedin',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
