# Generated by Django 4.0.1 on 2022-02-01 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bilgilerim', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Question',
            new_name='Hakkımda',
        ),
    ]
