# Generated by Django 4.0.1 on 2022-02-01 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bilgilerim', '0002_rename_question_hakkımda'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hakkımda',
        ),
    ]
