# Generated by Django 4.0.1 on 2022-02-08 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bilgilerim', '0004_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hakkımda',
            name='aciklama',
        ),
        migrations.AddField(
            model_name='hakkımda',
            name='ozgecmis',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
