# Generated by Django 4.0.1 on 2022-02-08 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bilgilerim', '0005_remove_hakkımda_aciklama_hakkımda_ozgecmis'),
    ]

    operations = [
        migrations.AddField(
            model_name='hakkımda',
            name='aciklama',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
