# Generated by Django 4.0.1 on 2022-02-08 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bilgilerim', '0006_hakkımda_aciklama'),
    ]

    operations = [
        migrations.AddField(
            model_name='hakkımda',
            name='anahtarkelime',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hakkımda',
            name='etiket',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
