# Generated by Django 4.0.1 on 2022-02-08 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bilgilerim', '0007_hakkımda_anahtarkelime_hakkımda_etiket'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hakkımda',
            old_name='aciklama',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='hakkımda',
            old_name='anahtarkelime',
            new_name='keywords',
        ),
        migrations.RenameField(
            model_name='hakkımda',
            old_name='isim',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='hakkımda',
            old_name='ozgecmis',
            new_name='personal_background',
        ),
        migrations.RenameField(
            model_name='hakkımda',
            old_name='soyisim',
            new_name='surname',
        ),
        migrations.RenameField(
            model_name='hakkımda',
            old_name='etiket',
            new_name='title',
        ),
    ]
