# Generated by Django 4.0.1 on 2022-02-08 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bilgilerim', '0008_rename_aciklama_hakkımda_description_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Hakkımda',
            new_name='About',
        ),
    ]
