# Generated by Django 4.0.1 on 2022-02-08 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bilgilerim', '0009_rename_hakkımda_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, upload_to='images/')),
                ('myimages', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bilgilerim.about')),
            ],
        ),
    ]
