# Generated by Django 4.0.1 on 2022-02-08 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bilgilerim', '0010_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='images',
            old_name='myimages',
            new_name='myimage',
        ),
    ]
