# Generated by Django 4.0.1 on 2022-02-13 02:54

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bilgilerim', '0012_alter_images_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='personal_background',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectname', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=300)),
                ('contentofproject', ckeditor_uploader.fields.RichTextUploadingField()),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('projectowner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bilgilerim.about')),
            ],
        ),
    ]
