# Generated by Django 4.0.1 on 2022-02-13 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bilgilerim', '0013_alter_about_personal_background_projects'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='job',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='projects',
            name='description',
            field=models.TextField(max_length=500),
        ),
    ]
