# Generated by Django 4.0.1 on 2022-02-22 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bilgilerim', '0016_languages_allworks'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
