# Generated by Django 4.0.1 on 2022-02-22 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bilgilerim', '0017_projects_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='images/')),
                ('myimage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bilgilerim.projects')),
            ],
        ),
    ]
