# Generated by Django 4.0.1 on 2022-02-22 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bilgilerim', '0018_projectimages'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='slug',
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
    ]
